apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
   env: prod
   app: main
   tier: frontend
   owner: Yauheni
spec:
  containers:
    - name: container-httpd
      image: httpd:alpine
      ports:
       - containerPort: 80

    - name: container-tomcat
      image: tomcat:alpine
      ports:
       - containerPort: 8080
